name: ArkTest
version: '${project.version}'
main: fr.skytryx.arktest.ArkTest
api-version: '1.20'
commands:
  createinstance:
    description: Command to create instances
    usage: "§3Usage: /createinstance <name>"
    aliases: [cinstance, createi]
    permission: arktest.command.createinstance
  deleteinstance:
    description: Command to delete instances
    usage: "§3Usage: /deleteinstance <name>"
    aliases: [dinstance, deletei]
    permission: arktest.command.deleteinstance
  listinstance:
    description: Command to get a list of all instances
    usage: "§3Usage: /listinstance"
    aliases: [listi, linstance]
  tpinstance:
    description: Command to teleport to an instance
    usage: "§3Usage: /tpinstance <name>"
    aliases: [tpi, teleporti, teleportinstance]
  download:
    description: Command to download the map you're in
    usage: "§3Usage: /download"
    aliases: [instancedownload, downloadinstance]
    permission: arktest.command.download